/** @flow */

/** name of this modules */
export const NAME = 'app';

/** action types */
export const ACTION_LIST_REQUEST = `${NAME}/ACTION_LIST_REQUEST`;

export const ACTION_DETAIL_REQUEST = `${NAME}/ACTION_DETAIL_REQUEST`;
export const ACTION_DETAIL_CLEAR = `${NAME}/ACTION_DETAIL_CLEAR`;
export const ACTION_DETAIL_WATCHED = `${NAME}/ACTION_DETAIL_WATCHED`;
export const ACTION_DETAIL_WISH = `${NAME}/ACTION_DETAIL_WISH`;

export const ACTION_LIST_ITEM_VISIT = `${NAME}/ACTION_LIST_ITEM_VISIT`;

export const ACTION_PROGRESS_WORKING = `${NAME}/ACTION_PROGRESS_WORKING`;
export const ACTION_PROGRESS_DESTROY = `${NAME}/ACTION_PROGRESS_DESTROY`;


