/** @flow */

/** name of this modules */
export const NAME = 'common'

/** action return type */
export type Action = {
  type: string,
  payload?: Object,
}

export type ActionAsync = (dispatch: Function, getState: Function) => void

/** action type */
export const ACTION_CACHE_CLEAR = `${NAME}/ACTION_CACHE_CLEAR`
export const ACTION_GUIDE_READ = `${NAME}/ACTION_GUIDE_READ`
export const ACTION_GUIDE_RESET = `${NAME}/ACTION_GUIDE_RESET`
export const ACTION_TAB_BAR_BADGE_SET = `${NAME}/ACTION_TAB_BAR_BADGE_SET`
export const ACTION_TAB_BAR_BADGE_CLEAR = `${NAME}/ACTION_TAB_BAR_BADGE_CLEAR`
export const ACTION_LOGIN = `${NAME}/ACTION_LOGIN`
export const ACTION_LOGOUT = `${NAME}/ACTION_LOGOUT`
export const ACTION_LOGIN_UPDATE = `${NAME}/ACTION_LOGIN_UPDATE`
export const ACTION_REGISTER_MOBILE_CHECK_SEND = `${NAME}/ACTION_REGISTER_MOBILE_CHECK_SEND`
export const ACTION_REGISTER_MOBILE_CHECK_SUC = `${NAME}/ACTION_REGISTER_MOBILE_CHECK_SUC`
export const ACTION_REGISTER_MOBILE_CHECK_RESET = `${NAME}/ACTION_REGISTER_MOBILE_CHECK_RESET`
export const ACTION_REGISTER_MOBILE_CHECK_COUNT = `${NAME}/ACTION_REGISTER_MOBILE_CHECK_COUNT`
export const ACTION_REGISTER_SUC = `${NAME}/ACTION_REGISTER`
export const ACTION_REGISTER_RESET = `${NAME}/ACTION_REGISTER_RESET`
export const ACTION_RESET_PASSWORD_MOBILE_CHECK_SEND = `${NAME}/ACTION_RESET_PASSWORD_MOBILE_CHECK_SEND`
export const ACTION_RESET_PASSWORD_MOBILE_CHECK_SUC = `${NAME}/ACTION_RESET_PASSWORD_MOBILE_CHECK_SUC`
export const ACTION_RESET_PASSWORD_MOBILE_CHECK_RESET = `${NAME}/ACTION_RESET_PASSWORD_MOBILE_CHECK_RESET`
export const ACTION_RESET_PASSWORD_MOBILE_CHECK_COUNT = `${NAME}/ACTION_RESET_PASSWORD_MOBILE_CHECK_COUNT`
export const ACTION_RESET_PASSWORD_SUC = `${NAME}/ACTION_RESET_PASSWORD_SUC`
export const ACTION_RESET_PASSWORD_RESET = `${NAME}/ACTION_RESET_PASSWORD_RESET`
export const ACTION_GESTURE_ENABLE = `${NAME}/ACTION_GESTURE_ENABLE`
export const ACTION_GESTURE_DISABLE = `${NAME}/ACTION_GESTURE_DISABLE`
export const ACTION_GESTURE_COUNT_RESET = `${NAME}/ACTION_GESTURE_COUNT_RESET`
export const ACTION_GESTURE_COUNT_DECREASE = `${NAME}/ACTION_GESTURE_COUNT_DECREASE`
export const ACTION_TOUCH_ID_SUPPORTED = `${NAME}/ACTION_TOUCH_ID_SUPPORTED`
export const ACTION_TOUCH_ID_ENABLE = `${NAME}/ACTION_TOUCH_ID_ENABLE`
export const ACTION_TOUCH_ID_DISABLE = `${NAME}/ACTION_TOUCH_ID_DISABLE`

/** URL type */
export const URL_DOWNLOAD = '/attachment/download.action'
export const URL_UPLOAD = '/attachment/upload.action'
export const URL_LOGIN = '/user/login'
export const URL_LOGOUT = '/user/logout'
export const URL_UPDATE_USER_INFO = '/user/updateUserInfo'
export const URL_REGISTER_MOBILE_CHECK_SEND = '/user/sendRegisterVerifyCode'
export const URL_REGISTER_MOBILE_CHECK = '/user/registerVerifyCode'
export const URL_REGISTER = '/user/register'
export const URL_RESET_PASSWORD_MOBILE_CHECK_SEND = '/user/sendResetVerifyCode'
export const URL_RESET_PASSWORD_MOBILE_CHECK = '/user/resetVerifyCode'
export const URL_RESET_PASSWORD = '/user/resetPassword'

/** 验证码失效时间(s) */
export const DURATION_MOBILE_CODE_EXPIRED = 12
