/** @flow */

/** name of this modules */
export const NAME = 'my'

/** action type */
export const ACTION_MOBILE_MODIFY_SEND = `${NAME}/ACTION_MOBILE_MODIFY_SEND`
export const ACTION_MOBILE_MODIFY_RESET = `${NAME}/ACTION_MOBILE_MODIFY_RESET`
export const ACTION_MOBILE_MODIFY_COUNT = `${NAME}/ACTION_MOBILE_MODIFY_COUNT`
export const ACTION_PROFILE_UPDATE = `${NAME}/ACTION_PROFILE_UPDATE`
export const ACTION_PROFILE_PATH_UPDATE = `${NAME}/ACTION_PROFILE_PATH_UPDATE`
export const ACTION_PROFILE_PATH_CLEAR = `${NAME}/ACTION_PROFILE_PATH_CLEAR`
export const ACTION_PROFILE_PHOTO_UPLOADED = `${NAME}/ACTION_PROFILE_PHOTO_UPLOADED`
export const ACTION_PROFILE_SWITCH = `${NAME}/ACTION_PROFILE_SWITCH`
export const ACTION_FEEDBACK = `${NAME}/ACTION_FEEDBACK`
export const ACTION_FEEDBACK_UPDATE = `${NAME}/ACTION_FEEDBACK_UPDATE`
export const ACTION_FEEDBACK_RESET = `${NAME}/ACTION_FEEDBACK_RESET`
export const ACTION_AUTO_LOGIN_ENABLE = `${NAME}/ACTION_AUTO_LOGIN_ENABLE`
export const ACTION_AUTO_LOGIN_DISABLE = `${NAME}/ACTION_AUTO_LOGIN_DISABLE`
export const ACTION_AUTO_LOGIN_STUB = `${NAME}/ACTION_AUTO_LOGIN_STUB`
export const ACTION_AUTO_LOGIN_SWITCH = `${NAME}/ACTION_AUTO_LOGIN_SWITCH`
export const ACTION_ABOUT_VERSION = `${NAME}/ACTION_ABOUT_VERSION`

/** URL type */
export const URL_APP_VERSION = '/index/appInfo'
export const URL_FEEDBACK = '/index/feedback'
export const URL_PASSWORD_MODIFY = '/user/modPassword'
export const URL_MOBILE_MODIFY_SEND = '/user/sendModPhoneVerifyCode'
export const URL_MOBILE_MODIFY = '/user/modPhoneVerifyCode'
export const URL_PROFILE = '/user/profile'
export const URL_PROFILE_UPDATE = '/user/updateProfile'



